LGUserBundle_homepage:
    pattern:  /
    defaults: { _controller: LGUserBundle:Default:index }

LGUserBundle_publicinfo:
    pattern:  /public
    defaults: { _controller: LGUserBundle:Unconnected:index }
