AppBundle_homepage:
    pattern:  /{visibility}
    defaults: { _controller: AppBundle:Default:index, visibility: private}
    requirements:
        visibility: public|private

AppBundle_login:
    pattern:  /login
    defaults: { _controller: AppBundle:Security:login}

AppBundle_logout:
    pattern:  /logout
    defaults: { _controller: FOSUserBundle:Security:logout}
